using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardDatabase : MonoBehaviour
{
    public static List<Card> cardsList = new List<Card>();

    private void Awake()
    {
        cardsList.Add(new Card(0, "Collaborator", 1, "This is code review", Resources.Load<Sprite>("1 CR"), 0, 1));
        cardsList.Add(new Card(1, "Crucible", 1, "This is code review", Resources.Load<Sprite>("2 CR"), 1, 2));
        cardsList.Add(new Card(2, "Gerrit", 1, "This is code review", Resources.Load<Sprite>("3 CR"), 2, 3));
        cardsList.Add(new Card(3, "Github CR", 1, "This is code review", Resources.Load<Sprite>("4 CR"), 3, 4));
        cardsList.Add(new Card(4, "Phabricator", 1, "This is code review", Resources.Load<Sprite>("5 CR"), 4, 5));
        cardsList.Add(new Card(5, "Collaborator", 1, "This is code review", Resources.Load<Sprite>("1 CR"), 0, 6));
        cardsList.Add(new Card(6, "Crucible", 1, "This is code review", Resources.Load<Sprite>("2 CR"), 1, 7));
        cardsList.Add(new Card(7, "Gerrit", 1, "This is code review", Resources.Load<Sprite>("3 CR"), 2, 8));
        cardsList.Add(new Card(8, "Github CR", 1, "This is code review", Resources.Load<Sprite>("4 CR"), 3, 9));
        cardsList.Add(new Card(9, "Phabricator", 1, "This is code review", Resources.Load<Sprite>("5 CR"), 4, 10));
        cardsList.Add(new Card(10, "Bitbucket", 1, "None", Resources.Load<Sprite>("1 VC"), 5, 11));
        cardsList.Add(new Card(11, "Github VC", 1, "None", Resources.Load<Sprite>("2 VC"), 6, 12));
        cardsList.Add(new Card(12, "Gitlab VC", 1, "None", Resources.Load<Sprite>("3 VC"), 7, 13));
        cardsList.Add(new Card(13, "Subversion", 1, "None", Resources.Load<Sprite>("4 VC"), 8, 14));
        cardsList.Add(new Card(14, "Bitbucket", 1, "None", Resources.Load<Sprite>("1 VC"), 5, 15));
        cardsList.Add(new Card(15, "Github VC", 1, "None", Resources.Load<Sprite>("2 VC"), 6, 16));
        cardsList.Add(new Card(16, "Gitlab VC", 1, "None", Resources.Load<Sprite>("3 VC"), 7, 17));
        cardsList.Add(new Card(17, "Subversion", 1, "None", Resources.Load<Sprite>("4 VC"), 8, 18));
        cardsList.Add(new Card(18, "Bamboo", 1, "None", Resources.Load<Sprite>("1 CN"), 9, 19));
        cardsList.Add(new Card(19, "Circle CI", 1, "None", Resources.Load<Sprite>("2 CN"), 10, 20));
        cardsList.Add(new Card(20, "Jenkins", 1, "None", Resources.Load<Sprite>("3 CN"), 11, 21));
        cardsList.Add(new Card(21, "TeamCity", 1, "None", Resources.Load<Sprite>("4 CN"), 12, 22));
        cardsList.Add(new Card(22, "Travis CI", 1, "None", Resources.Load<Sprite>("5 CN"), 13, 23));
        cardsList.Add(new Card(23, "Bamboo", 1, "None", Resources.Load<Sprite>("1 CN"), 9, 24));
        cardsList.Add(new Card(24, "Circle CI", 1, "None", Resources.Load<Sprite>("2 CN"), 10, 25));
        cardsList.Add(new Card(25, "Jenkins", 1, "None", Resources.Load<Sprite>("3 CN"), 11, 26));
        cardsList.Add(new Card(26, "TeamCity", 1, "None", Resources.Load<Sprite>("4 CN"), 12, 27));
        cardsList.Add(new Card(27, "Travis CI", 1, "None", Resources.Load<Sprite>("5 CN"), 13, 28));
        cardsList.Add(new Card(28, "Bugzilla", 1, "None", Resources.Load<Sprite>("1 BT"), 14, 29));
        cardsList.Add(new Card(29, "Jira", 1, "None", Resources.Load<Sprite>("2 BT"), 15, 30));
        cardsList.Add(new Card(30, "Lighthouse", 1, "None", Resources.Load<Sprite>("3 BT"), 16, 31));
        cardsList.Add(new Card(31, "Mantis", 1, "None", Resources.Load<Sprite>("4 BT"), 17, 32));
        cardsList.Add(new Card(32, "Bugzilla", 1, "None", Resources.Load<Sprite>("1 BT"), 14, 33));
        cardsList.Add(new Card(33, "Jira", 1, "None", Resources.Load<Sprite>("2 BT"), 15, 34));
        cardsList.Add(new Card(34, "Lighthouse", 1, "None", Resources.Load<Sprite>("3 BT"), 16, 35));
        cardsList.Add(new Card(35, "Mantis", 1, "None", Resources.Load<Sprite>("4 BT"), 17, 36));
        cardsList.Add(new Card(36, "Asana", 1, "None", Resources.Load<Sprite>("1 PM"), 18, 37));
        cardsList.Add(new Card(37, "Azure", 1, "None", Resources.Load<Sprite>("2 PM"), 19, 38));
        cardsList.Add(new Card(38, "Monday", 1, "None", Resources.Load<Sprite>("3 PM"), 20, 39));
        cardsList.Add(new Card(39, "Trello", 1, "None", Resources.Load<Sprite>("4 PM"), 21, 40));
        cardsList.Add(new Card(40, "YouTrack", 1, "None", Resources.Load<Sprite>("5 PM"), 22, 41));
        cardsList.Add(new Card(41, "Asana", 1, "None", Resources.Load<Sprite>("1 PM"), 18, 42));
        cardsList.Add(new Card(42, "Azure", 1, "None", Resources.Load<Sprite>("2 PM"), 19, 43));
        cardsList.Add(new Card(43, "Monday", 1, "None", Resources.Load<Sprite>("3 PM"), 20, 44));
        cardsList.Add(new Card(44, "Trello", 1, "None", Resources.Load<Sprite>("4 PM"), 21, 45));
        cardsList.Add(new Card(45, "YouTrack", 1, "None", Resources.Load<Sprite>("5 PM"), 22, 46));
        cardsList.Add(new Card(46, "HubSpot", 1, "None", Resources.Load<Sprite>("5 BT"), 42, 47));
        cardsList.Add(new Card(47, "HubSpot", 1, "None", Resources.Load<Sprite>("5 BT"), 42, 48));
        cardsList.Add(new Card(48, "AWS", 1, "None", Resources.Load<Sprite>("5 VC"), 43, 49));
        cardsList.Add(new Card(49, "AWS", 1, "None", Resources.Load<Sprite>("5 VC"), 43, 50));

        cardsList.Add(new Card(50, "Basic 1", 1, "None", Resources.Load<Sprite>("1 Basic"), 23, 51));
        cardsList.Add(new Card(51, "Basic 2", 1, "None", Resources.Load<Sprite>("2 Basic"), 24, 52));
        cardsList.Add(new Card(52, "Basic 3", 1, "None", Resources.Load<Sprite>("3 Basic"), 25, 53));
        cardsList.Add(new Card(53, "Basic 4", 1, "None", Resources.Load<Sprite>("4 Basic"), 26, 54));
        cardsList.Add(new Card(54, "Basic 5", 1, "None", Resources.Load<Sprite>("5 Basic"), 27, 55));
        cardsList.Add(new Card(55, "Basic 1", 1, "None", Resources.Load<Sprite>("1 Basic"), 23, 56));
        cardsList.Add(new Card(56, "Basic 2", 1, "None", Resources.Load<Sprite>("2 Basic"), 24, 57));
        cardsList.Add(new Card(57, "Basic 3", 1, "None", Resources.Load<Sprite>("3 Basic"), 25, 58));
        cardsList.Add(new Card(58, "Basic 4", 1, "None", Resources.Load<Sprite>("4 Basic"), 26, 59));
        cardsList.Add(new Card(59, "Basic 5", 1, "None", Resources.Load<Sprite>("5 Basic"), 27, 60));
        cardsList.Add(new Card(60, "Easy 1", 1, "None", Resources.Load<Sprite>("1 Easy"), 28, 61));
        cardsList.Add(new Card(61, "Easy 1", 1, "None", Resources.Load<Sprite>("2 Easy"), 29, 62));
        cardsList.Add(new Card(62, "Easy 1", 1, "None", Resources.Load<Sprite>("3 Easy"), 30, 63));
        cardsList.Add(new Card(63, "Easy 1", 1, "None", Resources.Load<Sprite>("4 Easy"), 31, 64));
        cardsList.Add(new Card(64, "Easy 1", 1, "None", Resources.Load<Sprite>("5 Easy"), 32, 65));
        cardsList.Add(new Card(65, "Easy 1", 1, "None", Resources.Load<Sprite>("1 Easy"), 28, 66));
        cardsList.Add(new Card(66, "Easy 1", 1, "None", Resources.Load<Sprite>("2 Easy"), 29, 67));
        cardsList.Add(new Card(67, "Easy 1", 1, "None", Resources.Load<Sprite>("3 Easy"), 30, 68));
        cardsList.Add(new Card(68, "Easy 1", 1, "None", Resources.Load<Sprite>("4 Easy"), 31, 69));
        cardsList.Add(new Card(69, "Easy 1", 1, "None", Resources.Load<Sprite>("5 Easy"), 32, 70));
        cardsList.Add(new Card(70, "Hard 1", 1, "None", Resources.Load<Sprite>("1 Hard"), 33, 71));
        cardsList.Add(new Card(71, "Hard 1", 1, "None", Resources.Load<Sprite>("2 Hard"), 34, 72));
        cardsList.Add(new Card(72, "Hard 1", 1, "None", Resources.Load<Sprite>("3 Hard"), 35, 73));
        cardsList.Add(new Card(73, "Hard 1", 1, "None", Resources.Load<Sprite>("4 Hard"), 36, 74));
        cardsList.Add(new Card(74, "Hard 1", 1, "None", Resources.Load<Sprite>("5 Hard"), 37, 75));
        cardsList.Add(new Card(75, "Hard 1", 1, "None", Resources.Load<Sprite>("1 Hard"), 33, 76));
        cardsList.Add(new Card(76, "Hard 1", 1, "None", Resources.Load<Sprite>("2 Hard"), 34, 77));
        cardsList.Add(new Card(77, "Hard 1", 1, "None", Resources.Load<Sprite>("3 Hard"), 35, 78));
        cardsList.Add(new Card(78, "Hard 1", 1, "None", Resources.Load<Sprite>("4 Hard"), 36, 79));
        cardsList.Add(new Card(79, "Hard 1", 1, "None", Resources.Load<Sprite>("5 Hard"), 37, 80));
        cardsList.Add(new Card(80, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 81));
        cardsList.Add(new Card(81, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 82));
        cardsList.Add(new Card(82, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 83));
        cardsList.Add(new Card(83, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 84));
        cardsList.Add(new Card(84, "Basic 6", 1, "None", Resources.Load<Sprite>("6 Basic"), 39, 85));
        cardsList.Add(new Card(85, "Basic 6", 1, "None", Resources.Load<Sprite>("6 Basic"), 39, 86));
        cardsList.Add(new Card(86, "Basic 7", 1, "None", Resources.Load<Sprite>("7 Basic"), 40, 87));
        cardsList.Add(new Card(87, "Basic 7", 1, "None", Resources.Load<Sprite>("7 Basic"), 40, 88));
        cardsList.Add(new Card(88, "Basic 8", 1, "None", Resources.Load<Sprite>("8 Basic"), 41, 89));
        cardsList.Add(new Card(89, "Basic 8", 1, "None", Resources.Load<Sprite>("8 Basic"), 41, 90));

        cardsList.Add(new Card(90, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 91));
        cardsList.Add(new Card(91, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 92));
        cardsList.Add(new Card(92, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 93));
        cardsList.Add(new Card(93, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 94));
        cardsList.Add(new Card(94, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 95));
        cardsList.Add(new Card(95, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 96));
        cardsList.Add(new Card(96, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 97));
        cardsList.Add(new Card(97, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 98));
        cardsList.Add(new Card(98, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 99));
        cardsList.Add(new Card(99, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 100));
        cardsList.Add(new Card(100, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 101));
        cardsList.Add(new Card(101, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 102));
        cardsList.Add(new Card(102, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 103));
        cardsList.Add(new Card(103, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 104));
        cardsList.Add(new Card(104, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 105));
        cardsList.Add(new Card(105, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 106));
        cardsList.Add(new Card(106, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 107));
        cardsList.Add(new Card(107, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 108));
        cardsList.Add(new Card(108, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 109));
        cardsList.Add(new Card(109, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 110));
        cardsList.Add(new Card(110, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 111));
        cardsList.Add(new Card(111, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 112));
        cardsList.Add(new Card(112, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 113));
        cardsList.Add(new Card(113, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 114));
        cardsList.Add(new Card(114, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 115));
        cardsList.Add(new Card(115, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 116));
        cardsList.Add(new Card(116, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 117));
        cardsList.Add(new Card(117, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 118));
        cardsList.Add(new Card(118, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 119));
        cardsList.Add(new Card(119, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 120));
        cardsList.Add(new Card(120, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 121));
        cardsList.Add(new Card(121, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 122));
        cardsList.Add(new Card(122, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 123));
        cardsList.Add(new Card(123, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 124));
        cardsList.Add(new Card(124, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 125));
        cardsList.Add(new Card(125, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 126));
        cardsList.Add(new Card(126, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 127));
        cardsList.Add(new Card(127, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 128));
        cardsList.Add(new Card(128, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 129));
        cardsList.Add(new Card(129, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 130));
        cardsList.Add(new Card(130, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 131));
        cardsList.Add(new Card(131, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 132));
        cardsList.Add(new Card(132, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 133));
        cardsList.Add(new Card(133, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 134));
        cardsList.Add(new Card(134, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 135));
        cardsList.Add(new Card(135, "Upgrade Card", 1, "None", Resources.Load<Sprite>("7"), 38, 136));
    }
}
